openapi: 3.0.0
servers: []
info:
  version: 1.0.0
  title: Plane Maintenance
tags: 
  - name: BE+
  - name: DAWA
  - name: ACD
  - name: BLG
  - name: BE
paths: 
  /repairs:
    post:
      tags: 
        - DAWA
      description: Create a repair request
      responses: 
        '200':
          description: request successful
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/%s'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/%s'
        required: true
    get:
      tags: 
        - DAWA
      description: Read all repair requests
      responses: 
        '200':
          description: request successful
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/%s'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/%s'
        required: true
    put:
      tags: 
        - DAWA
      description: Update a repair request
      responses: 
        '200':
          description: request successful
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/%s'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/%s'
        required: true
components:
  schemas: 